global using Xunit;
global using Moq;
global using Shouldly;
global using TycoonFactoryApp.Domain;
global using TycoonFactoryApp.Core.Models;
global using TycoonFactoryApp.Core.Processors;
global using AutoMapper;
global using TycoonFactoryApp.Core.MappingProfile;
global using TycoonFactoryApp.Core.Contracts.DataServices;
